### ISSUE TITLE
Add blog post

### ISSUE THREAD

**Issue by JohnVeness** [Metalnem/edge-magazine-downloader#1]
Many thanks for this tool. I suggest you add a link to your blog post (https://mijailovic.net/2017/01/22/removing-edge-magazine-drm/) to the readme, or possibly better, put the text of the blog post directly in the repo, e.g. as a markdown file, for more posterity (blogs can disappear).

**Comment by Metalnem** [comment]
I did that, thanks. I didn't bother with the README file before because I didn't expect that anybody would see it, to be honest :)

Text of the blog post is already in the different repository (I'm using GitHub Pages to serve the blog). You can find it [here](https://github.com/Metalnem/mijailovic.net/tree/gh-pages).
