### ISSUE TITLE
Any more "platforms" than "iphone-retina"?

### ISSUE THREAD

**Issue by JohnVeness** [Metalnem/edge-magazine-downloader#2]
I'm interested in the parameter "platform: iphone-retina". Are there any more valid values for that parameter, do you know? I'm wondering if that parameter might control the level of quality of the PDF, e.g. dpi on images.

**Comment by Metalnem** [comment]
That parameter is required in the request, but is completely ignored by the server. You can put anything there and the result would still be the same file.

More interesting one is the appKey, because Future PLC has separate apps for all of their magazines, and I think that it selects the magazine you want to download, but that is completely different thing from what you needed here.
